# Generated by Django 6.0.6 on 2026-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exam_end_time_exam_published_exam_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/'),
        ),
    ]
